version: '1'
services:
  microservice:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@wmtrtppfeqwrrw3c_low?TNS_ADMIN=/app/Wallet_WMTRTPPFEQWRRW3C
      - spring.datasource.username=FSI_MS_BD
      - spring.datasource.password=ClaseFullStack123-
    restart: always